version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] PHP version (use -bullseye variants on local arm64/Apple Silicon): 8, 8.0, 7, 7.4, 7.3,
        # 8-bullseye, 8.0-bullseye, 7-bullseye, 7.4-bullseye, 7.3-bullseye, 8-buster, 8.0-buster, 7-buster,
        # 7.4-buster, 7.3-buster
        # https://mcr.microsoft.com/v2/vscode/devcontainers/php/tags/list
        VARIANT: "8.1-bullseye"
        MEMORY_LIMIT: ${MEMORY_LIMIT-512M}
    restart: unless-stopped
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    depends_on:
      db:
        condition: service_healthy
    command: apache2-foreground
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      DRUSH_ALLOW_XDEBUG: 1

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -udrupal -pdrupal -e 'use drupal' || exit 1"]
      interval: 3s
      timeout: 60s
      retries: 40
      start_period: 20s
    command: --default-authentication-plugin=mysql_native_password --transaction-isolation=READ-COMMITTED  --max-connections=2300
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped

  redis:
    image: redis:7.0.8-alpine
    command: >
      --maxmemory-policy volatile-lru
      --maxmemory 256M
    restart: unless-stopped

volumes:
  mysql-data: null
